services:
  trades-app:
    image: trades-app:1.0.0
    #image: trades-app:latest
    build: .
    container_name: trades-app
    ports:
      - "8080:8080"
    volumes:
      - tradesdb:/data
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/tradesdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

volumes:
  tradesdb: