services:
  trades-app:
    build: .
    container_name: trades-app
    ports:
      - "8080:8080"
    volumes:
      - tradesdb:/data
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/tradesdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""

volumes:
  tradesdb: